# Uncomment the next line to define a global platform for your project
# platform :ios, '8.0'

target 'lijiababy' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for lijiababy
  pod 'LBXScan'
  pod 'JPush','~> 3.0.5'
  pod 'FFDropDownMenu'
  pod 'MBProgressHUD', '~> 1.0.0'
end
