platform :ios, "8.0"

pod 'AFNetworking', '~> 3.0'
pod 'MJRefresh', '~> 2.4.7'
pod 'MJExtension', '~> 2.5.9'
pod 'SDWebImage', '~> 3.7.3'
pod 'XLForm', '~> 3.0.2'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'HMSegmentedControl', '~> 1.5.2'
pod 'SDCycleScrollView', '~> 1.3'
pod 'EAIntroView', '~> 2.7.4'
pod 'MarqueeLabel', '~> 2.2.5'


target :ZiZhiGZWTests, :exclusive => true do
# pod 'Kiwi'
end